const Courses = () => {
  return <section id="courses">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et nisl convallis, elementum justo non, dignissim mi. Vivamus sollicitudin mi tortor, vitae egestas metus lobortis vitae. In mattis metus lectus, sit amet accumsan tortor tristique eleifend. Aenean varius, lectus ut suscipit blandit, leo ligula posuere augue, at egestas augue enim sagittis mauris. Cras efficitur convallis purus nec bibendum. Integer molestie arcu mattis purus condimentum, eu aliquet nunc mattis. Nam elementum finibus sem. Sed dictum tortor enim, quis tincidunt quam tempor sit amet. Suspendisse suscipit laoreet libero, ac posuere ligula blandit non. Nulla consectetur sem eu pellentesque sodales. Phasellus sem enim, sollicitudin a est pharetra, efficitur cursus felis. Nam gravida id sem id dictum. Nunc congue sit amet arcu quis ultrices. Aliquam quis interdum nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse posuere ante ac risus pretium efficitur.

Quisque a est cursus, eleifend turpis sit amet, accumsan velit. Praesent auctor arcu eget sapien fermentum convallis. Nulla at eleifend velit. Pellentesque interdum, metus a tristique placerat, sem erat semper erat, a luctus felis erat a nunc. Duis ipsum nisi, lobortis vitae commodo eget, ultricies in eros. Curabitur euismod molestie mauris, nec faucibus risus porta at. Phasellus auctor gravida magna at sagittis.

Cras tristique lectus eros, et suscipit nisi condimentum cursus. Nunc porta felis eu tellus consectetur, id sollicitudin ligula rhoncus. Praesent suscipit porta ultricies. Cras venenatis lectus a tellus facilisis eleifend. Morbi interdum lorem sed tortor accumsan consequat. Nullam efficitur erat quis lacus feugiat, eu bibendum diam efficitur. Maecenas accumsan condimentum risus, ac condimentum diam euismod eu. Cras ac cursus eros. Aenean magna massa, placerat quis sollicitudin id, varius nec massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed elit arcu, lacinia in orci vitae, mollis molestie risus. Etiam tempor urna nec dolor ullamcorper, id maximus ipsum sollicitudin.

Phasellus non sapien ex. Aliquam ut convallis nibh. Proin hendrerit sapien a dolor blandit, non tincidunt diam lobortis. Aenean nec dui in nulla rhoncus commodo. Vestibulum sit amet auctor magna, eu sagittis mi. Ut laoreet nec nisi ac sodales. In rutrum augue eu sagittis rhoncus. Donec auctor nec metus et auctor. Etiam id arcu eleifend, convallis metus vitae, dictum velit. Etiam eget consectetur lacus, non pulvinar nulla. Quisque ornare elementum odio, eget imperdiet turpis gravida at. Sed nec massa sed libero ullamcorper semper eu vitae nunc. Praesent et ligula tortor.

Pellentesque vehicula, nunc eget luctus blandit, ipsum risus molestie lorem, in interdum quam nisl et eros. Etiam semper, velit eu consectetur vehicula, mauris felis interdum mauris, eget eleifend nulla erat et sem. Vestibulum pellentesque tellus quam, vulputate vehicula dolor pharetra non. Nullam quam magna, scelerisque vel fermentum in, volutpat sit amet sem. Suspendisse turpis magna, volutpat quis fermentum ut, iaculis a arcu. Suspendisse scelerisque nunc a vestibulum aliquet. Morbi vulputate, justo sit amet venenatis viverra, augue turpis blandit justo, vitae placerat lectus justo eu tellus. Sed suscipit luctus diam id rhoncus. Aenean libero sapien, blandit eu risus id, gravida consectetur ligula. Integer sed laoreet odio. Curabitur dapibus ex ut mattis tempus. Vestibulum eu condimentum nisl. Sed vel feugiat nisl, ut ullamcorper ligula. Suspendisse potenti. Sed fermentum est eget neque auctor consectetur. Nunc eget consequat massa, eget lobortis lorem.


  </section>;
};
export default Courses;
